### ISSUE TITLE
Create kubernetes cluster with 0 worker nodes

### ISSUE THREAD

**Issue by tanandy** [ovh/public-cloud-roadmap#131]
As a MKS administrator
I want to spawn Kubernetes cluster with 0 nodes in the pool
So that I can just create worker nodes after cluster creation with a correct name.

note: alternative is to allow us to choose name for nodes at cluster creation to avoid having wrongly named node

**Comment by mhurtrel** [comment]
Hi @tanandy .
Thanks for the spot.
I confirm this is an unwated regression from our UI. I will immeditaly create an internal bug to be corrected, so that we allow back creation with no nodes.

In the meantime, please node you can use the API :
![image](https://user-images.githubusercontent.com/24432524/134017735-79c84d87-b747-40e5-bfc2-3cefd96e5f97.png)
send an empty "nodepool" object in the https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/kube#POST endpoint

**Comment by tanandy** [comment]
thank you

**Comment by tanandy** [comment]
I can confirm it works , thank you :)

Could you also add the possibility to choose default node pool name and also edit it later.
