### ISSUE TITLE
Object Storage - asynchronous replication

### ISSUE THREAD

**Issue by Izaia64** [ovh/public-cloud-roadmap#179]
As a user I want to be able to replicate object storage between regions
I want to be able to consume these features through standard APIs / OVHcloud Customer panel
Replication between 2 buckets, asynchronous replication (aprox. 15 minutes)

We will enable automatic and asynchronous replication of objects contained inside a source bucket to one or more destination buckets. Those destination buckets can be in one single region or dispatched throughout several regions according to your needs.

Async replication will allow customers to:
- make exact copies of objects (all metadata will also be replicated)
- address synchronization of data between several teams use cases
- transition copies of your data into other storage classes to optimize costs
- augment high resiliency by having your data replicated across multiple regions

What will be provided is a S3 compatible REST API to put, delete, download a replication configuration file that allows for definition of :
- destination buckets
- filters to select which objects to replicate
- rule priorities

The following configuration elements will be supported:
- replication to multiple destination buckets (including delete operation)
- replication to buckets located across multiple regions

The following configuration will NOT be supported for now:
- replication to buckets owned by a different account (destination buckets are not owned by the same account that owns the source bucket)
- transition copies to COLD STORAGE (deep archive) class
- transition to other storage classes
- retrieval of replication metrics (Nb of objects pending replication, Bytes pending replication, Operations failed replication, Replication latency (delta between buckets), Thoughput)
- replication of existing objects i.e objects that were present before replication was applied

**Comment by Izaia64** [comment]
This feature is in development and targeted for Q4 2022

**Comment by loliee** [comment]
This feature will not be compliant with `SSE-C` encrypted objects right ? 
It will be compliant with [SSE-S3](https://github.com/ovh/public-cloud-roadmap/issues/324) encrypted objects ?

Thanks

**Comment by lason-ovh** [comment]
> This feature will not be compliant with `SSE-C` encrypted objects right ? It will be compliant with [SSE-S3](https://github.com/ovh/public-cloud-roadmap/issues/324) encrypted objects ?
> 
> Thanks

Hi, this feature will not be compliant with SSE-C nor SSE-S3 for now: 
- for SSE-C, additional work will be needed so in the first iteration, it will not be supported yet
- SSE-S3 (and SSE-KMS) is a feature not available yet

Hope it helps

**Comment by lenglet-k** [comment]
Hi, have you any news for this feature ?

**Comment by lason-ovh** [comment]
> Hi, have you any news for this feature ?

Hi, as previously stated, this feature is due in Q2 2023 (May)

**Comment by loliee** [comment]
Hi, is this feature available in an alpha or beta version ?
Thanks

**Comment by biapar** [comment]
Ready?

**Comment by JustDoItSascha** [comment]
> > Hi, have you any news for this feature ?
> 
> Hi, as previously stated, this feature is due in Q3 2023

I love how you made Q2 from @Izaia64 to Q3. And now we have Q4 and there is no update :(

**Comment by agoude** [comment]
Hi @JustDoItSascha, well thanks for your patience and highlighting the lighter side of the situation ;)
The team has been pushing hard rebuilding the feature to make it better and ensuring the performance/resilience levels we wanna reach: the main reason behind those different shifts and we are sorry for such delays!

The wait has been longer than expected and we're working to make it worth your wait. Now, I can only say we never been so closed to deploy it and i'll keep you posted with a solid and hopefully final ETA 🙏! (

**Comment by JustDoItSascha** [comment]
Ok cool, thank you :)

**Comment by mahmoudaljan** [comment]
@agoude Thank you for the hard work. We are eager to get our hands on the feature. I know that for us, this will make our lives much easier. Don't hesitate to share an ETA if you have any.

**Comment by agoude** [comment]
> @agoude Thank you for the hard work. We are eager to get our hands on the feature. I know that for us, this will make our lives much easier. Don't hesitate to share an ETA if you have any.

hey @mahmoudaljan we all agree on this feature importance, no doubt! As I said earlier, we will shortly keep you posted with a solid ETA! thanks!

**Comment by lason-ovh** [comment]
Hi @everyone, I wanted to ask: since the replication applies to only new objects i.e objects that are added AFTER the replication configuration is uploaded, we were wondering the importance of replicating the objects that already exist in the bucket.
- on a scale of 1 (not important) to 5 (mandatory feature), what is for you the importance of providing a tool/mechanism to automatically replicate existing objects?
- on a scale of 1 (I don't mind) to 5 (I'd hate to), should we provide that tool, do you mind executing a (very) few command lines?

**Comment by biapar** [comment]
+4
+4 but better by control panel.

**Comment by mahmoudaljan** [comment]
@lason-ovh 

- 5 :  You must assume that every client who needs this feature will look for ways to achieve this, better to deal with it on your own terms (bandwidth...) and limit complaints and questions due to client mishaps while trying to achieve this on their own.

- 2 : Since this will only be a procedure that will be executed once, no one will lack motivation to make it work at the beginning even if it requires a multi step procedure with command lines. Also, please do provide an API call if possible.

**Comment by 131** [comment]
* 5
* 2 // do whatever you want as long as terraform can apply it

**Comment by lenglet-k** [comment]
- 5
- 2

**Comment by JustDoItSascha** [comment]
* 5
* 5

**Comment by fredleger** [comment]
> @lason-ovh
> 
> * 5 :  You must assume that every client who needs this feature will look for ways to achieve this, better to deal with it on your own terms (bandwidth...) and limit complaints and questions due to client mishaps while trying to achieve this on their own.
> * 2 : Since this will only be a procedure that will be executed once, no one will lack motivation to make it work at the beginning even if it requires a multi step procedure with command lines. Also, please do provide an API call if possible.

- 5
- 2 (as long as we can automate it in some way like script or jobs in our own infra)

**Comment by mahmoudaljan** [comment]
@agoude A little humor doesn't hurt.

![Uploading giphy.gif…]()

**Comment by lason-ovh** [comment]
It's finally happening!!!! 😮 😮  The long awaited ASYNCHRONOUS REPLICATION will be very soon open in BETA (ETA = W14). You can already suscribe via the following link to be among our early users: https://survey.ovh.com/index.php/192786
Once the feature is activated, we will let you know. As always, we are keen on receiving your feedbacks, so do not  hesitate! 😉

**Comment by martonivan** [comment]
Do you already have an estimated schedule about when the feature is expected to reach the 1.0 production phase?

**Comment by lason-ovh** [comment]
Hello everyone!

It is with great pleasure to announce that the long-awaited feature of Asynchronous Replication on S3 is finally in production! Thanks to this feature, our customers will be able to make automated serverside copies of their data stored in S3, thus answering to backup/DPR, geo-redundancy and failover issues, without having to worry about egress fees and replication failure recovery, which is automatic and transparent.

Documentation has already been posted [here](https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062417) since the opening of the beta.


If you have any questions, please don't hesitate to contact us on [Discord ](https://discord.com/channels/850031577277792286/893523544846270504)
