### ISSUE TITLE
CoreDNS configmap (coredns, in kube-system namespace) overwrite

### ISSUE THREAD

**Issue by kalos** [ovh/public-cloud-roadmap#184]
Hi.
I noticed that with each patch/update the Corefile configmap is overwritten.

Is there any way to avoid this or to include other configmaps?

AKS and DigitalOcean adopts an interesting solution: https://docs.digitalocean.com/products/kubernetes/how-to/customize-coredns/

Is there a similar function on ovh?

Is it possible to expect a change to the default Corefile similar to the one in the DO site?

**Comment by mhurtrel** [comment]
Hello @JulienCharge  I confirm this will be supported but I can't yet share an ETA. Will try to get one and update this task, sorry for the delay.

**Comment by Grounz** [comment]
Hello @mhurtrel  have you a news on this topic ?

**Comment by d--j** [comment]
> I suggest to use DigitalOcean convention `"custom/*.override"` for default server block and `"custom/*.server"` for additional server block. Name of configmap: `coredns-custom`.

looks like that is the same as what [AKS does](https://docs.microsoft.com/en-us/azure/aks/coredns-custom). I think OVH should stick with that naming scheme, too.

**Comment by lenglet-k** [comment]
Hi @mhurtrel 
have you any news ?

**Comment by mhurtrel** [comment]
Hello @lenglet-k Our Current ETA is October, hopefully early in the month.

**Comment by jMonsinjon** [comment]
We are doing our best to deploy this feature end of September or early October (available through API)

**Comment by jMonsinjon** [comment]
Hello,
This feature has been released but the documentation is still in progress.

On every new K8S cluster, or after an update, the new CoreDNS config will include an expansion mechanism.
You can see now a new configmap named 'coredns-custom' that can be modified to add your specific configuration.
The original coredns config must still not be changed because we can reset it at any time.

For example
`
$ kubectl -n kube-system edit cm coredns-custom
...
data:
  example.server: |
    my-custom-domain.local.:53 {
    forward . [my-custom-dns-server-private-ip]
  }
`

**Comment by scraly** [comment]
Hi,
A new tutorial about how to customize CoreDNS have been released:
https://docs.ovh.com/gb/en/kubernetes/customizing-coredns/
🙂
