### ISSUE TITLE
MongoDB offers with more storage by default

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#231]
## User Story ##
As a customer
I want to get more storage space by default
So that
I not scared of missing disk space for my workloads

## Acceptance criterias ##
- storage size selection during cluster creation
- available for all service plans (Essentials, Business, Enterprise)
- same storage space for all nodes
- accepted limitation : unable to hot-resize it.
- accepted limitation : performances may not be as good as local storage, but has to be documented
- accepted change : slight price increase (to be defined)

### New default storage values ###

| Reference  | Compute | Current Storage | New Storage |
| --- | --- | --- | --- |
| Db1-2  | 2 GB RAM / 1 vCore | 25 GB | 40 GB |
| Db1-4  | 4 GB RAM / 2 vCores | 50 GB | 80 GB |
| Db1-7  | 7 GB RAM / 2 vCores | 50 GB | 160 GB |
| Db1-15  | 15 GB RAM / 4 vCores | 100 GB | 320 GB |
| Db1-30  | 30 GB RAM / 8 vCores | 200 GB | 640 GB |
| Db1-60  | 60 GB RAM / 16 vCores | 400 GB | 1.28 TB |
| Db1-120  | 120 GB RAM / 32 vCores | 800 GB | 2.56 TB |

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by thild42** [comment]
Since Tuesday, February 7, 2023, MongoDB services are now available with more storage by default. This new storage is based on remote disk of first generation, second generation will be made available progressively region by region. That also mean that local SSD storage is not available for order anymore, cluster currently using local SSD will be able to migrate in the near future. Relying on remote disk also mean that MongoDB services will benefit from Flex Disk (#143) that will soon be release (tune in next week 😉).
