### ISSUE TITLE
Openstack - Enable Internal DNS Resolution

### ISSUE THREAD

**Issue by fawben** [ovh/public-cloud-roadmap#340]
If two vms are created on the same private network, they should be able to be mutually reachable through a logical name, 
rather than their IP address only.
This is to avoid the modification of /etc/hosts file on the vm instances, or manage entries on an external DNS.
The name is in the form of 'host-%(octet0)s-%(octet1)s-%(octet2)s-%(octet3)s.openstacklocal', ie 'host-192-168-0-4.openstacklocal'

[https://specs.openstack.org/openstack/charm-specs/specs/pike/implemented/internal-dns.html](https://specs.openstack.org/openstack/charm-specs/specs/pike/implemented/internal-dns.html
)

**Comment by yomovh** [comment]
Thanks for the issue and sorry to answer you so late. I will add it the the backlog for analysis.

**Comment by yomovh** [comment]
@matmicro  this DNS geo routing could be part of our [DNS server product](https://www.ovhcloud.com/en-ie/domains/dns-server/) roadmap. However, we do not intent to work on that in the next 12 months. 

I will keep the issue open for the initial request : be able to resolve internally instance hostnames.

**Comment by anthonyroussel** [comment]
Hello, do you have any idea when [OpenStack Designate](https://docs.openstack.org/designate/latest/) will be available in OVH Public Cloud, to internally resolve DNS records inside an OpenStack project?

**Comment by yomovh** [comment]
Hello,

About the initial request, this feature is already available & supported since it is openstack upstream feature.
In order to use it, you need to enable DHCP on your subnet and leave the dns-nameservers empty[1] : at instance boot, the DHCP will configure your instance to use the default local DNS (usually the 2 first IP of your CIDR).
then the instance spawned on this subnet will have a local dns entry on 'host-%(octet0)s-%(octet1)s-%(octet2)s-%(octet3)s.openstacklocal', ie 'host-192-168-0-4.openstacklocal'

[1] When creating a private network and subnet using the OVHcloud Control Panel, you may notice that the default DNS nameserver is set to OVHcloud's public DNS (`213.186.33.99`). Unfortunately, this default setting cannot be overridden within the Control Panel at the moment. If you wish to use internal DNS resolution, you will need either to remove the default nameserver  in your subnet configuration (through the Horizon web portal or the Command Line Interface (CLI) or manually configure in your instances the DNS resolution.

About an internal DNS service like [Openstack Designate](https://docs.openstack.org/designate/latest/intro/index.html) that enables user to specify private dns records, this is not something we plan to provide in the mid term.

See on ubuntu 22.04

```bash
~$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (ens3)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
**Current DNS Server: 10.0.1.3**
       DNS Servers: 10.0.1.3 10.0.1.2
        DNS Domain: openstacklocal  
```
Then local DNS is configured correctly.

```bash
dig host-10-0-1-73.openstacklocal

; <<>> DiG 9.18.28-0ubuntu0.22.04.1-Ubuntu <<>> host-10-0-1-73.openstacklocal
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55685
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;host-10-0-1-73.openstacklocal.	IN	A

;; ANSWER SECTION:
host-10-0-1-73.openstacklocal. 0 IN	A	10.0.1.73

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Oct 01 09:14:43 UTC 2024
;; MSG SIZE  rcvd: 74
  
```
