### ISSUE TITLE
Managed Private Registry backup and fork

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#381]
As a Managed Private Registry user
I would like to be able to setup an option to get automated backup in another region.
And then ability to create a new MPR from that backup.

**Comment by mhurtrel** [comment]
Hello @matmicro

I understand the need of having a DRP solution for Managed Private Registry, however I think the best approach would be to document and leverage the built-in feature of Harbor for this. This would allow us to focus on other features, while embracing our "reversibility" value, because this allow customer to use another Harbor deployment at OVHcloud or anywhere else.

Please consult this documentation to see how to enable continuous replication between 2 or multiple Harbor instances : https://goharbor.io/docs/2.4.0/administration/configuring-replication/create-replication-rules/

We are conscious that today we only have a single region for the service, but we plan to have 2 additionnal ones : one in Canada  and a second one in Europe, based in Germany. Both are currently planned in May : https://github.com/ovh/public-cloud-roadmap/issues/79 and https://github.com/ovh/public-cloud-roadmap/issues/239#issuecomment-1310674740

Can you confirm this will fit your requirements or detail why not ?

**Comment by mhurtrel** [comment]
Closing this ticket as we now have multiple regions open (France, Canada and Germany), and there is native replication feature available in harbor https://goharbor.io/docs/2.5.0/administration/configuring-replication/ .
