### ISSUE TITLE
Managed Private Registry downgrade

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#389]
As a Managed Private Registry user,
I would like to be able to downgrade an offer.

For example i am using Plan M, and as my disk usage is low enough to fit Plan S, i would like to be able to downscale.

**Comment by mhurtrel** [comment]
Hi @matmicro 

Though I understand the specific use casew we see a general trend un regsitries growing and quasi never decreasing their storage. Because this feature is not so easy (for example it would mean deactivating the vulnerability scanning for M tobS migration and having explicit agreement of customer of loosing associated configuration and data) and we have numerous features with much more demand and value in backlog, I anticipate we will not developp this.

Remember that Harbor allow replication and you are billed bybthe ourn donnote hésitate to createba smaller plan, migrate the data you want and delete the bigger service if needed.
