### ISSUE TITLE
[Managed Kubernetes Service] Add persistent local storage partitions on worker instances

### ISSUE THREAD

**Issue by rverchere** [ovh/public-cloud-roadmap#420]
Hello,

For some applications, using local-storage as storage provider makes sense (i.e. database with a lot of IOPS).
Worker instances have high-speed local disks, but there is only 1 `/` partition which is used by the system. So, if I choose a B2-60 instance for my nodepool, 400 GB SSD disk is unused.

It should be usefull to split disk with 2 partitions, to use free available storage, and avoir loosing data after cluster upgrade.

I know there are some instances is additionnal NVMe additionnal disks, but it would be nice to have persistent parititions for all instances.

**Comment by LisaPerrier** [comment]
Hello @rverchere, thank you for your feedback on this matter. We will take a closer look at it and let you know if a solution can be found and implemented.
In the meantime you can look at this doc for a workaround https://help.ovhcloud.com/csm/en-ie-public-cloud-kubernetes-formating-nvme-disk-iops-nodes?id=kb_article_view&sysparm_article=KB0037312 and let us know how it went

**Comment by rverchere** [comment]
Hi @LisaPerrier, I've tested successfully this workaround. But that's too bad to not use the local storage which is empty (only system and logs).

**Comment by mhurtrel** [comment]
Hi @rverchere 

After assessing options and effort associated, we unfortunately decided not to developp this feature.
But mid term, we have great news to share with you as we will have a more elegant solution to cover youuse case more elegantly.

Here is the full details about our decision :
- In the mid term (to our current knowledge, second par of 2024 calendar year), OVHcloud public cloud will leverage a great NVME-over-Fabric tehcnology to completely decouple storage from compute VMS.
This means that all our instances (and therefor Kubernetes worker nodes) will be booted from a small but very performant distant system disk (in terms of I/O and latency), and you will be able to add such disks as additionnal disk (this last feature should be able a bit earlier, first par of 2024).
Those will combine performance that can be compared to local disks, while offering better resistance to incidents and flexbility associated to distant disks.
- The current implementation of public cloud do not allow us to preserve data on local disks when a VM is migrated after an incident affecting the physical disks of a machine. We feel that advertising the use of those local disks for workloads data would encourage risky behaviours.
- Dissociating system partition from a local ephemeral partition requires significant effort. Furthermore that effort would be trashed a few months after release will be "trashed because no longer relevant when we will have NVME-over-fabric system disks. Though it would bring some value for your use case a few months sooner, we found the same effort to bring more value for more use case in a shorter time frame and had to make the hard choice to not developp this.

I hope you understand our position and we encourage you to bear with us. My colleague @JacquesMrz will soon create public issues for upcoming NVMe-over-Fabric disks as additionnal and base system disks.
