### ISSUE TITLE
Shared Resources - New Range of Instances

### ISSUE THREAD

**Issue by JacquesMrz** [ovh/public-cloud-roadmap#46]
New Range of Public Cloud Instances with shared resources.

**Comment by mhurtrel** [comment]
Since late this week, new "discovery" instances are available.
They will progressively replace the "sandbox" ones. Though their ressources are not dedicated (contrary to all other families), you will see a strong performance improvement over sandbox ones .

The website will be update soon, and the instances will be progressively open in all regions.

Note that D2-4 and D2-8 will also be usage with Kubernetes in a few weeks.

![image](https://user-images.githubusercontent.com/24432524/111043681-116e0e80-8444-11eb-89ac-2d63678eab2a.png)

**Comment by JacquesMrz** [comment]
Why did we release D2 Range without the relevant Website content ?

Due to last week incident, we need to mobilize all the capacity available to help our customers to restart their services.
Meanwhile, should you have any questions regarding this new range, please ask it here.

**Comment by drzraf** [comment]
I'm sorry to comment here about something apparently more related to sales & business model than actual technical aspects but since you said _"should you have any questions regarding this new range, please ask it here."_, I'll just do it and express my preference of the cheap S1 range:

I heavily rely on the **sandbox** range (~ 10 instances) for public facing services. With some automation, it's the most secure container orchestration out there. The _sandbox_ range allows a variety of applications for personal/family/intranet use : The S1-2 at 3.5€/mo (the cheapest one), is really a good choice for self-hosting starters and represents the floor price for an datacenter-hosted, always-on service (commercially comparable to Free 2h).

The new advertised replacement (D2-2) comes at 6.5€/mo with a doubled CPU which is probably going to be underused most of the time : As you know, with low-end hosting configurations memory matters **much** more than CPU and since 10GB of storage was already enough for most operating systems, the +15GB, while nice to have, does not seem significant (Those already relying on external volumes would continue to do so)

Overall I mostly see a price-increase range (GB/mem price) which I see as regression
- +66% S1-2 -> D2-2
- +43% S1-4 -> D2-4
- +38% S1-8 -> D2-8

And since the _sandbox_ range is cheap and well-tailored (and their resources _not guaranteed_ in the first place), I'd be sad to see them go (Should it really be removed??)

Basically, with S1-2 you could host a mailserver, owncloud, passbolt, and many other data-related services in a **cheap** way, and the CPU was still enough to do some (non-intensive) SSL (fallback VPN, reverse-proxy) for family-usage and you'd still scale to S1-4 for 8€/mo. I you dare fine-tuning the app, you could really get a lot from them.
D2-2 / D2-4 configuration get us a (non-guaranteed) dual-core for computing (SSL or headless mathematica?), with the same amount of memory for 66% price increase.


**Suggestion**: While you could disable _sandbox_ from the UI, could you still maintain the flavor via OpenStack (API, os cli, Horizon, ...) so that current users and power-users could still rely on this (nice) offer.

One positive point of the _Discovery_ brand: D2-4 and D2-8 having the same storage size _may_ in theory allow smooth **downgrade** (But wrt downgrade, the dream feature still lives at https://github.com/ovh/public-cloud-roadmap/issues/71)

**Comment by StephenLittBelch** [comment]
> **Suggestion**: While you could disable _sandbox_ from the UI, could you still maintain the flavor via OpenStack (API, os cli, Horizon, ...) so that current users and power-users could still rely on this (nice) offer.

Please consider retaining the S1 instances alongside the D2’s. I run into many non-IO or CPU-intensive tasks (like small offsite-backup and monitoring servers) which the S1’s are perfect for, while the D2’s are very interesting for replacing some VPS servers, such as DNS and email gateways.

**Comment by srekcud** [comment]
I got this error when I try to update one of our S1-2 instances: 

You cannot resize from flavor s1-2 to flavor d2-2. Acceptable flavors for this image: [[u'c2-15', u'b2-120-flex', u's1-8', u'c2-15-flex', u'r2-240-flex', u'b2-120', u'r2-15-flex', u'c2-30', u'b2-30', u'b2-60', u'r2-15', u'c2-7', u'b2-15', u'c2-30-flex', u'b2-30-flex', u'r2-120-flex', u'c2-7-flex', u'c2-60', u'r2-30-flex', u'c2-120-flex', u'r2-240', u's1-4', u'b2-7', u'b2-60-flex', u'b2-7-flex', u'r2-120', u'r2-60-flex', u'r2-30', u'b2-15-flex', u'r2-60', u'c2-120', u'c2-60-flex', u's1-2']]

**Comment by JacquesMrz** [comment]
@srekcud , you are right, it should be possible.
We identified the missing conf. The team is on it, I'll get back to you as soon as it's fixed.

**Comment by JacquesMrz** [comment]
@srekcud, it is fixed now. Everyone can update the flavor of his public cloud instance from S1 range to D2 range, as long as the disk size of the D2 flavor is at least as big.

**Comment by srekcud** [comment]
Thank you @JacquesMrz
