### ISSUE TITLE
[Public Cloud Load Balancer] New flavor (XL)

### ISSUE THREAD

**Issue by hadrien-f** [ovh/public-cloud-roadmap#460]
As an Public Cloud service user,

I am asked to upgrade our server infrastructure in order to face a very high burst of requests.

The load would be for exemple 100 000 people redirected to our website at a specific time.

If I understand correctly the informations of https://www.ovhcloud.com/en-gb/public-cloud/load-balancer/ a load balancer of Size L can handle 1000 SSL connection per second*. Users would need to wait up to 100 seconds before being all connected.

I would like to have an XL and if possible XXL load balancer flavor capable of handling a bigger load.

Thank you,

**Comment by yomovh** [comment]
The new XL flavor is out 🥳 

It is available in all public cloud regions and through all the current control plane interfaces:
* OVHcloud control panel
* Openstack GUI (Horizon)
* Openstack CLI
* Terraform (openstack provider)
* Managed Kubernetes Service annotation (see this [doc](https://help.ovhcloud.com/csm/en-gb-public-cloud-kubernetes-expose-applications-using-load-balancer?id=kb_article_view&sysparm_article=KB0062867))

Performances are provided [here](https://www.ovhcloud.com/en/public-cloud/load-balancer/)
Note that those values are for information only since the load balancer performances can vary depending on a range of incoming traffic factors. Hence we recommend to benchmark the load balancer with traffic representative of your use case.
