### ISSUE TITLE
S3 IP restrictions

### ISSUE THREAD

**Issue by LuckyFrost** [ovh/public-cloud-roadmap#495]
As an OVHcloud customer using s3 object storage
I want to be able to restrict access to the s3 service by IP address
So that I have a extra level of security.

---
**Description:**
In many cases, it is not possible to hide access keys securely enough: they can be available to the developer in his project, or they can be available to administrators who manage services that use the keys.
To prevent the possibility of information leakage and/or other possibility of using the service for unauthorized purposes, a good option would be to
1) Restrict access by IP
2) And a less flexible, but also an option that would be nice to have: restrict access for use only in vrack

**Comment by agoude** [comment]
hello @LuckyFrost! thanks for your feedback! We already have another topic close to your issue: https://github.com/ovh/public-cloud-roadmap/issues/260 but the scope is wider than just IP restrictions.
For you to know, we are currently discussing this topic internally and we could consider offering IP whitelisting as a quick win. 
That's why we are going to keep this issue for now and we might refine the user story in a second phase!
Cheers,

**Comment by lason-ovh** [comment]
Hi @LuckyFrost regarding your second point, you might be intererested in [this issue](https://github.com/ovh/public-cloud-roadmap/issues/400) that would restrict S3 access to servers from vrack only.

**Comment by lason-ovh** [comment]
this issue will be implemented in #260 and #400
