### ISSUE TITLE
Kubernetes Control Plane Audit Logs

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#51]
As a Managed Kubernetes admin
I want to tail the logs of the different components of my control plane (scheduler, APIserver...)
to understand a problematic behaviour

Notes :
Managed Kubernetes users can also use this tutorial to gather and anylse their data plane logs in OVHcloud logs data platform : https://docs.ovh.com/fr/logs-data-platform/kubernetes-fluent-bit/

**Comment by mhurtrel** [comment]
This feature should be available in the control panel late this month

**Comment by mhurtrel** [comment]
The feature should be available in a couple of days.

**Comment by mhurtrel** [comment]
The feature should be prodded on Monday

**Comment by mhurtrel** [comment]
The feature is now available from the control panel .

![image](https://user-images.githubusercontent.com/24432524/114368397-abc58d00-9b7d-11eb-80eb-3f646abd89d8.png)

Note : in the mid term we will allow the selection of a time range to navigate logs in the previous days.
in the long term feature OVHcloud will offer a general integrated observability solution, gathering logging, traces and metrics of all ou IaaS and PaaS solutions. Comments are still welcome for continuous improvement.

**Comment by Choem** [comment]
As a cluster administrator I'm seriously unsatisfied by this solution for managed services. One of our clients wants to complete one of their ISO regulations. We want to help them programatically by collecting the logs via Fluent-bit and Falco then plot the logs with Graylog or Kibana. Falco takes care of the security in runtime which is really important for us. But there are zero ways of configuring the kube-apiserver in the control-plane. Because of this we won't be able to see who creates, updates or deletes k8s resources. The logs in the "Audit logs" tab shown above aren't a good solution. How would we be able to get notified when for example a pod gets compromised?

Is there anything planend in the near future regarding this issue?

**Comment by Choem** [comment]
As a cluster administrator I'm seriously unsatisfied by this solution for managed services. 

One of our clients wants to complete one of their ISO regulations. We want to help them programatically by collecting the logs via Fluent-bit and Falco then plot the logs with Graylog or Kibana. Falco takes care of the security in runtime which is really important for us. But there are zero ways of configuring the kube-apiserver in the control-plane. Because of this we won't be able to see who creates, updates or deletes k8s resources. 

The logs in the "Audit logs" tab shown above aren't a good solution. How would we be able to get these logs within our cluster? Is there anything plannend in the near future regarding this issue?

**Comment by ToonvanStrijp** [comment]
@mhurtrel how do I access these logs from within my cluster? Cause I don't have access to the control plane. I'm looking for possibilities to integrate with https://falco.org/

**Comment by mhurtrel** [comment]
Hi Chiem and Toon I confirm we are aware of those limitations and plan to offer observability accross all iaas and paas products in the ou lic cloud universe, including capacity to forward control plane logs to external plateforms and tools. This is a large project that will start in 2022.
