### ISSUE TITLE
Reset MKS node

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#515]
As a MKS user i would like to be able to reset a node.
I am facing some nodes with "no space left on device" and thus any new pod is starting.

As the node is monthly billed, i don't want to delete it.
So i need to be able to reset that pod in order the reinit everything.

**Comment by antonin-a** [comment]
Hello @matmicro, this kind of requirement is already identified but the solution will be provided from billing side: 
We plan to launch a new billing solutions called "saving plans", it will allows customers to apply reservation (montly, yearly,...) on flavors instead of instances.

In other words, you will be able to delete/create your mks nodes without impact on billing side/double billing. 

While we are developing this feature, and for you specific case, you can ask for a voucher in order to compensate the over billing.
