### ISSUE TITLE
Smaller Cloud Instances

### ISSUE THREAD

**Issue by roybj** [ovh/public-cloud-roadmap#73]
Would like to see smaller instances available in Public Cloud like 1CPU/2GB RAM, 2CPU/4GB RAM etc.

**Comment by mhurtrel** [comment]
Hi @roybj 




We heard your. since late this week, new "discovery" instances are available.
They will progressively replace the "sandbox" ones. Though their ressources are not dedicated (contrary to all other families), you will see a strong performance improvement over sandbox ones .

Note that D2-4 and D2-8 will also be usage with Kubernetes in a few weeks.
![image](https://user-images.githubusercontent.com/24432524/111043599-a3c1e280-8443-11eb-8266-a45d44fdde3f.png)

**Comment by matmicro** [comment]
Can you provide an ETA for d2-4 and d2-8 usage on Kubernetes ?
I am currently not able to get it working through kubectl.

**Comment by mhurtrel** [comment]
Hi @matmicro we have had to delay the launch within Kubernetes to ensure right ressource sizing and great performance/stability. The feature will be avilable in a few weeks. you can follow that dedicated entry : https://github.com/ovh/public-cloud-roadmap/issues/19
