### ISSUE TITLE
Is anybody listening to this panel?

### ISSUE THREAD

**Issue by dantart** [ovh/public-cloud-roadmap#75]
My feature request is to have more activity in this panel.
This should be a super active place, because we are the hard-users of Public Cloud asking for new things to improve the product, but I don't see activity, and the little that has been done is to open zones and improve Kubernetes, but Public Cloud is 19 products more than Kubernetes.
I don't know, I get the impression that this place is forgotten.

**Comment by telenieko** [comment]
> I don't know, I get the impression that this place is forgotten.

As far as I've seen it is more used to keep track of feature requests and let you "kinda" know about their progress. More or less like Microsoft's UserVoice. You do get word of when something is implemented and/or available or requests for testers. Though not of much use as lots of items in "Coming soon ~2 months" stay there for way more than that.

This could be a place of vibrant feedback loops between OVH and its customers. Some place to help better define the product while allowing clients to plan ahead with reliable release planning (ie: make "Coming soon" really mean 2 months.)

Right know it just feels as if somebody is dumping here their backlog and doing random updates from time to time.

Specific examples where improvements could be worked:
- #50, where concern is shown regarding OVHs OpenStack version lags bu no conversation starts.

The eternal "Coming Soon" which should have a much better communication. That's supposed to be 2 months, if it cannot be achieved something should be said (otherwise we are left wondering about OVH's planning capabilities):

- #24, nov'20 "for January", feb'21 "beta in couple weeks". march'21 no beta announced.
- #40, virtual routers. Coming soon since nov'20. Users ask about the delay, no answer.
- #15, vRack on k8s. Coming soon since oct'20. Atleast here there **is** an update: should be around the corner. 
- #19, smaller worker nodes, since nov'20. Friend of #46 also since dec'20.

**Comment by mhurtrel** [comment]
Hi @telenieko  and @dantart .

Tough to hear, as me, @baaastijn (working on IA/ML/Data) and @JacquesMrz (working on Compute, STorage an Network) do indeed hear and read you as often as we can.

This place is really not forgotten, and we will make sure we reflect that event better.

Concerning https://github.com/ovh/public-cloud-roadmap/issues/24 https://github.com/ovh/public-cloud-roadmap/issues/17, https://github.com/ovh/public-cloud-roadmap/issues/15 and https://github.com/ovh/public-cloud-roadmap/issues/19 , I simply was away from job and keyboard for a couple of weeks, bu will update them immediately.

**Comment by telenieko** [comment]
> This place is really not forgotten, and we will make sure we reflect that event better.

Thank you for the quick feedback on this. 
Must say I really love OVH above any other Cloud.

> Concerning #24 #17, #15 and #19 , I simply was away from job and keyboard for a couple of weeks, bu will update them immediately.

welcome back!

**Comment by dantart** [comment]
Also tough to say @mhurtrel , I recommend you more "action" to show. 10 messages in 2021.
I also love OVH above other clouds @telenieko ... but I would really like more action in the community.
