### ISSUE TITLE
Support VolumeSnapshot of in-use volumes

### ISSUE THREAD

**Issue by lchdev** [ovh/public-cloud-roadmap#77]
Hi,

We would like to be able to take volume snapshots of _in-use_ volumes, which is currently not possible. 

This requires a parameter on the VolumeSanpshotClass used by he `cinder-csi-plugin`: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#supported-parameters.

Thanks

**Comment by mhurtrel** [comment]
Hi @lchdev We need our Ifrastructure teams to update the Cinder version to support this . I add it to the mid term backlog, and we should generalize this as soon as https://github.com/ovh/public-cloud-roadmap/issues/50 is closed

**Comment by lchdev** [comment]
Thanks for the feedback :)

**Comment by alainabbas** [comment]
hello 
I try to run K10 frem veeam (kasten.io) and seems they need their improvment

**Comment by evaldass** [comment]
hi,
this problem is still relevant, so it would be great to put more effort into updating the required components, because this feature is critical to having a system with backup solution.

**Comment by alainabbas** [comment]
Hello 
the snapshots work if the pvc is not in use but doesnt work if it is in use. Backup are critial. We tested on the Scaleway's kubernetes and it runs well ! we plan to quit OVH' cloud not a good solution without have backup ...

**Comment by scndel** [comment]
Hi, OVH support oriented me towards https://docs.ovh.com/gb/en/kubernetes/backing-up-volumes-using-stash/ but definitely a built-in recurring snapshot for PV would be a killing feature for a Managed Kubernetes.
I understand that currently you rely on the global _Cinder_ infrastructure.
May I suggest that you could create a **third** _storage class_ to bind volumes with an independent storage infrastructure ? Therefore you could already start to implement the tool & us to test it as an alpha feature without waiting for such a massive & slow (24 Nov 2020 !) update from #50 and without any breaking change for existing volumes.

**Comment by mhurtrel** [comment]
Hello and sorry for the delay on this.
We confirmed that a recent version of the Cinder CSI, in OVHcloud regions were Openstack Stein as been deployed, supports this feature. We will be running extensive testing to make sure this does not have any regression impact, and plan to deliver this feature either late Apreil or May. We plan to have all regions support this at the time we will have it deployed.

Additionnaly, please note that we now support live resize of volumes on Stein regions

**Comment by mhurtrel** [comment]
Hello to everyone following this issue ! The CSI update that will enable the VolumeSnpahot feature for in-use volumes is to be prodded within the next 10 days. Note that this will enable the feature for all Openstack regions running Stein. This is the case for most regions, and will be the case for all regions within summer.

**Comment by mhurtrel** [comment]
We just upgraded the cinder CSI.
This upgrade will benefit all customers on supported Kubernetes versions (1.20+) . **All new clusters** will natively have it, and for **existing clusters, customers will need to run the patch upgrade** (for exemple through the notification that appear on his cluster page). 
Here is a detail of all improvments and new use cases :

**Hot snapshot** ; capacity to snapshot a volume in use : This is key as it enable the use of all K8s compliant Backup and DRP tools such as Trillio and Kasten . This means that Kubernetes can call the snapshot feature from Cinder, while a block is being used. NOTE THAT THIS REQUIRES TO BE ON A STEIN REGION . On other regions, only cold snapshots are supported. : https://github.com/ovh/public-cloud-roadmap/issues/77
**Hot resize :** this enables the capacity to grow a volume/block, while being in use NOTE THAT THIS REQUIRES TO BE ON A STEIN REGION. On other regions, only cold resisizes are supported.
**Volumes metrics** will now be accessible from APIserver : https://github.com/ovh/public-cloud-roadmap/issues/166 so that customers can anticipate when he will miss space on a volume for example.
**This also fixes the "SecurityContextFs" bug** that blocked many Helm charts to be deployed without a trick : https://docs.ovh.com/sg/en/kubernetes/persistentvolumes-permission-errors/

Documentation will be updated in the upcoming weeks to reflect those changes.

Here is the list of regions (where the Managed Kubernetes product is present) on OpenStack Stein:

GRA5 , GRA9, SBG5
BHS5
WAW1
DE1
UK1 (region will be made available in the upciming days)

Regions still on OpenStack Newton (upgrade will be finalized this summer, more info will be published here : https://public-cloud.status-ovhcloud.com/ and by email to customers with these active regions)

GRA7 (Stein upgrade planned on 2022-05-31)
SYD1 (APAC)
SGP1 (APAC)
VA1 (US)
OR1 (US)
