### ISSUE TITLE
API + console Audit Logs

### ISSUE THREAD

**Issue by tanandy** [ovh/public-cloud-roadmap#93]
As a user I want to be able to audit events what happened on OVH API or web console
I want to be able to consume these features through standard APIs / OVHcloud Customer panel
Then i will be able to follow unexpected behavior on OVH cloud for security reasons and to improve governance

**Comment by mhurtrel** [comment]
Hello @tanandy 

I confirm we fully understand the need for this feature and this is being adressed at OVHcloud level (not specifically in the public-cloud universe this github project concerns).

Note that there is already a minimal implementation of this available to use : 
 - https://api.ovh.com/console/#/me/api/logs/services#GET will give you a list of ID corresponding to all actions performed on the API on the product you are owner of.
 - https://api.ovh.com/console/#/me/api/logs/services/{logId}#GET  will give you detail on a given line, including the hour, the route used and the nic (ovh account).
 
I know this is not ideal in terms of user experience (you have to loop on the first table to then search a given event) and this has some limitations, for example you dont get parameter details for a given line, and only write actions are logged. In case you need to investigate on one of this action, I think you could open a ticket to support who has access to more information.

I close this ticket because it does not fit the public cloud scope but let it open to comments if you wish to share more information. I will also ping my colleague working on observability features. who will be interested in more details like the pical retention you would be looking for, the capacity to forward those logs to a Log Data Platform (OVHCloud one or another ? etc ).

**Comment by tanandy** [comment]
ok. but where can i follow the progress on that topic ?

I would like a default free offer that basically allow us to  display, search , and download the events in the past 90 days. Additional features could come later.

**Comment by mhurtrel** [comment]
@tanandy currently this public roadmap initiative on Github is scope to the services in the OVHcloud public cloud universe. We hope that the great quality of your participation will help us have the same thing for other OVHcloud teams ;)
